# Generated by Django 4.1.7 on 2023-10-09 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlantSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('watering_frequency', models.IntegerField()),
                ('soil_mix', models.CharField(choices=[('sandy', 'Sandy'), ('loamy', 'Loamy'), ('clay', 'Clay'), ('peaty', 'Peaty')], max_length=20)),
                ('soil_conditions', models.CharField(choices=[('well_drained', 'Well-Drained'), ('moist', 'Moist'), ('dry', 'Dry')], max_length=20)),
                ('light_conditions', models.CharField(choices=[('full_sun', 'Full Sun'), ('partial_sun', 'Partial Sun'), ('shade', 'Shade')], max_length=20)),
                ('toxicity_to_animals', models.CharField(choices=[('none', 'None'), ('dog', 'Dog'), ('cat', 'Cat')], default='none', max_length=20)),
            ],
        ),
    ]
