# Generated by Django 4.1.7 on 2023-10-13 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_plantprofile_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantprofile',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.plantspecies'),
        ),
    ]
